/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { Color, MeshStandardMaterial } from "three";
import { useMaterialStore, useConfigSteps } from "../UI/EditUI";
import * as THREE from "three";

export default function Glove(props) {
  const { nodes, materials } = useGLTF("./models/glove_uv.glb");

  const normalMap = useTexture("./textures/nleather5.png");
  const palmbackNormal = useTexture("./textures/nleather5.png");

  const steps = useConfigSteps((state) => state.steps);
  const color = useMaterialStore((state) => state.color);
  const isMetallic = useMaterialStore((state) => state.isMetallic);

  const fistRef = useRef();
  const thumbRef = useRef();
  const wristRef = useRef();
  const PalmWristRef = useRef();
  const insideThumbRef = useRef();
  const trimRef = useRef();
  const lacesRef = useRef();
  const thumbConnectRef = useRef();

  // Update materials dynamically based on steps and state
  useEffect(() => {
    palmbackNormal.wrapS = THREE.RepeatWrapping;
    palmbackNormal.WrapT = THREE.RepeatWrapping;
    palmbackNormal.needsUpdate = true;

    const updateMaterial = (ref) => {
      if (ref.current) {
        ref.current.material.color = new Color(color);
        ref.current.material.roughness = isMetallic ? 0.2 : 0.4;
        ref.current.material.metalness = isMetallic ? 0.8 : 0.0;
      }
    };

    switch (steps) {
      case 0:
        updateMaterial(fistRef);
        break;
      case 1:
        updateMaterial(thumbRef);
        break;
      case 2:
        updateMaterial(wristRef);
        break;
      case 4:
        updateMaterial(PalmWristRef);
        break;
      case 5:
        updateMaterial(insideThumbRef);
        break;
      case 6:
        updateMaterial(thumbConnectRef);
        break;
      case 7:
        updateMaterial(trimRef);
        break;
      case 8:
        updateMaterial(lacesRef);
        break;
      default:
        break;
    }
  }, [color, isMetallic, steps]);

  // Dynamically update wrist material
  const wristMat = useMemo(() => {
    const mat = materials.Wrist.clone();
    mat.color = new Color(color); // Dynamically update color
    mat.roughness = isMetallic ? 0.4 : 0.8;
    mat.metalness = isMetallic ? 0.6 : 0.0;
    mat.needsUpdate = true;
    return mat;
  }, [color, isMetallic, materials.Wrist]);

  const otherMaterials = useMemo(() => {
    return {
      palmbackMat: new MeshStandardMaterial({ normalMap: palmbackNormal }),
      thumboutMat: new MeshStandardMaterial({ normalMap: normalMap }),
      wristbackMat: new MeshStandardMaterial({ normalMap: normalMap }),
      PalmWristMat: new MeshStandardMaterial({ normalMap: normalMap }),
      insideThumbMat: new MeshStandardMaterial({ normalMap: normalMap }),
      trimMat: new MeshStandardMaterial({ normalMap: normalMap }),
      lacesMat: new MeshStandardMaterial({ normalMap: normalMap }),
      thumbConnectMat: new MeshStandardMaterial({ normalMap: normalMap }),
    };
  }, [normalMap, palmbackNormal]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.black.geometry}
        material={materials["Material.001"]}
        position={[0.004, -0.57, 0.137]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palmback.geometry}
        material={otherMaterials.palmbackMat}
        ref={fistRef}
        position={[0, 0.141, 0.173]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wristback.geometry}
        material={otherMaterials.wristbackMat}
        position={[0, 0.141, 0.173]}
        ref={wristRef}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piping.geometry}
        material={otherMaterials.trimMat}
        ref={trimRef}
        position={[0.002, -0.601, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stitches.geometry}
        material={materials["Material.014"]}
        position={[-0.013, -0.153, -0.017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tstrip.geometry}
        material={otherMaterials.thumbConnectMat}
        position={[0, 0, 0.209]}
      />
      <group position={[0, 0.097, 0.173]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_15.geometry}
          ref={PalmWristRef}
          material={otherMaterials.PalmWristMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_15_1.geometry}
          material={materials.Holes}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.connect.geometry}
        material={otherMaterials.thumbConnectMat}
        ref={thumbConnectRef}
        position={[-0.621, 1.295, -0.279]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.thumbin.geometry}
        material={otherMaterials.insideThumbMat}
        ref={insideThumbRef}
        position={[-0.426, 0.593, -0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.thumbout.geometry}
        material={otherMaterials.thumboutMat}
        position={[-0.799, 0.327, 0.173]}
        ref={thumbRef}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lace_left.geometry}
        material={otherMaterials.lacesMat}
        ref={lacesRef}
        position={[0.01, -0.76, -0.201]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lace_right.geometry}
        material={otherMaterials.lacesMat}
        position={[0.01, -0.76, -0.201]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.madeforchampions.geometry}
        material={wristMat} // Use the wrist material for text
        position={[0.008, -0.942, 0.559]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.564}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Flag}
        position={[0.018, -1.431, 0.373]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.786}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["HECHO EN MEXICO"]}
        position={[0.018, -1.431, 0.363]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.334, 0.648, 0.067]}
      />
    </group>
  );
}

useGLTF.preload("./models/glove_uv.glb");
