/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glove.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.black.geometry}
        material={materials['Material.001']}
        position={[0.004, 1.081, 0.137]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.p4.geometry}
        material={materials['Material.002']}
        position={[-0.801, 1.979, 0.173]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.p2.geometry}
        material={materials['Material.004']}
        position={[-0.01, 0.636, 0.338]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.p1.geometry}
        material={materials['Material.005']}
        position={[-0.047, 2.311, -0.192]}
        scale={1.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.p5.geometry}
        material={materials['Material.007']}
        position={[-0.047, 2.311, -0.192]}
        scale={1.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palmback.geometry}
        material={materials['Material.010']}
        position={[0, 1.793, 0.173]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wristback.geometry}
        material={materials['Material.011']}
        position={[0, 1.793, 0.173]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piping.geometry}
        material={materials['Material.012']}
        position={[0.002, 1.051, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stitches.geometry}
        material={materials['Material.014']}
        position={[-0.013, 1.498, -0.017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tstrip.geometry}
        material={materials['Material.015']}
        position={[0, 1.651, 0.209]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm.geometry}
        material={materials['Material.016']}
        position={[0, 1.748, 0.173]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.connect.geometry}
        material={materials['Material.017']}
        position={[-0.621, 2.946, -0.279]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.thumbin.geometry}
        material={materials['Material.018']}
        position={[-0.426, 2.245, -0.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.thumbout.geometry}
        material={materials['Material.020']}
        position={[-0.799, 1.979, 0.173]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lace_left.geometry}
        material={materials['Material.021']}
        position={[0.01, 0.891, -0.201]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lace_right.geometry}
        material={materials['Material.021']}
        position={[0.01, 0.891, -0.201]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
    </group>
  )
}

useGLTF.preload('/glove.glb')
